- hosts: all
  remote_user: root
  vars:
    email: alberto@dyne.org
  tasks:
  - name: Configuration for nginx
    blockinfile:
      dest: /etc/nginx/conf.d/{{ domain_name }}.conf
      create: true
      block: |
        server {
          listen 80;
          listen [::]:80;
          root /var/www/html;
          server_name {{ domain_name }};
        }

  - name: Remove default config for nginx
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: Restart nginx
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: yes
      name: nginx

  - apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - certbot
      - python3-certbot-nginx

  - name: Obtain SSL/TLS certificate
    command: "certbot certonly --non-interactive --agree-tos -m {{ email }} --nginx -d {{ domain_name }}"
